name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_DB: forumapi_test
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: supersecretpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: localhost
      PGUSER: developer
      PGPASSWORD: supersecretpassword
      PGDATABASE: forumapi_test
      PGPORT: 5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U developer; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run migrations (optional)
        run: |
          npm run migrate up

      - name: Run tests
        run: npm run test
